// Sample products with style data for testing style filtering
const sampleLensProducts = [
  {
    id: 'lens-1',
    name: 'FreshKon Mosaic Contact Lenses',
    price: 4500,
    category: 'Contact Lenses',
    brand: 'FreshKon',
    material: 'Hydrogel',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Natural Brown',
    image: '/images/freshkon-mosaic.jpg',
    colors: [
      { name: 'Natural Brown', hex: '#8B4513' },
      { name: 'Honey', hex: '#FFA500' },
      { name: 'Gray', hex: '#808080' },
      { name: 'Blue', hex: '#0000FF' }
    ],
    sizes: ['8.4mm', '14.2mm'],
    lensTypes: ['Daily', 'Monthly'],
    features: ['UV Protection', 'Moisture Lock'],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: 'In Stock',
    description: 'Premium colored contact lenses with natural look and comfort.',
    style: 'Natural',
    gallery: ['/images/freshkon-mosaic-color-ainak.pk_.jpg', '/images/contact-lenses-solution-bottle-banner_33099-1916.jpg'],
    featured: true,
    bestSeller: true
  },
  {
    id: 'lens-2',
    name: 'Acuvue Oasys Clear Lenses',
    price: 3200,
    category: 'Transparent Lenses',
    brand: 'Acuvue',
    material: 'Silicone Hydrogel',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Clear',
    image: '/images/contact-lenses-solution-bottle-banner_33099-1916.jpg',
    colors: [{ name: 'Clear', hex: 'transparent' }],
    sizes: ['8.4mm', '14.0mm'],
    lensTypes: ['Bi-weekly', 'Monthly'],
    features: ['UV Protection', 'High Oxygen Permeability'],
    discount: { hasDiscount: true, discountPercentage: 15 },
    status: 'In Stock',
    description: 'Crystal clear prescription lenses for everyday wear.',
    style: 'Classic',
    gallery: ['/images/freshkon-mosaic.jpg'],
    featured: false,
    bestSeller: true
  },
  {
    id: 'lens-3',
    name: 'Bella Elite Colored Contacts',
    price: 2800,
    category: 'Colored Lenses',
    brand: 'Bella',
    material: 'Hydrogel',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Emerald Green',
    image: '/images/freshkon-mosaic-color-ainak.pk_.jpg',
    colors: [
      { name: 'Emerald Green', hex: '#50C878' },
      { name: 'Sapphire Blue', hex: '#0F52BA' },
      { name: 'Amethyst Purple', hex: '#9966CC' },
      { name: 'Hazel Brown', hex: '#8E7618' }
    ],
    sizes: ['8.6mm', '14.2mm'],
    lensTypes: ['Daily', 'Monthly'],
    features: ['Natural Look', 'Comfortable Wear'],
    discount: { hasDiscount: true, discountPercentage: 20 },
    status: 'In Stock',
    description: 'Vibrant colored contact lenses for a dramatic look.',
    style: 'Bold',
    gallery: ['/images/freshkon-mosaic.jpg', '/images/contact-lenses-solution-bottle-banner_33099-1916.jpg'],
    featured: true,
    bestSeller: false
  },
  {
    id: 'lens-4',
    name: 'Dailies AquaComfort Plus',
    price: 3800,
    category: 'Transparent Lenses',
    brand: 'Alcon',
    material: 'Nelfilcon A',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Clear',
    image: '/images/contact-lenses-solution-bottle-banner_33099-1916.jpg',
    colors: [{ name: 'Clear', hex: 'transparent' }],
    sizes: ['8.7mm', '14.0mm'],
    lensTypes: ['Daily'],
    features: ['Triple Comfort', 'Moisture Release'],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: 'In Stock',
    description: 'Daily disposable lenses with superior comfort.',
    style: 'Comfort',
    gallery: ['/images/freshkon-mosaic.jpg'],
    featured: false,
    bestSeller: true
  },
  {
    id: 'lens-5',
    name: 'Solotica Natural Colors',
    price: 5200,
    category: 'Contact Lenses',
    brand: 'Solotica',
    material: 'Polymacon',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Mel Honey',
    image: '/images/freshkon-mosaic.jpg',
    colors: [
      { name: 'Mel Honey', hex: '#D2691E' },
      { name: 'Ocre', hex: '#CC7722' },
      { name: 'Quartzo', hex: '#C0C0C0' },
      { name: 'Cristal', hex: '#E6E6FA' }
    ],
    sizes: ['8.6mm', '14.2mm'],
    lensTypes: ['Annual'],
    features: ['Natural Enhancement', 'Brazilian Quality'],
    discount: { hasDiscount: true, discountPercentage: 10 },
    status: 'In Stock',
    description: 'Premium Brazilian colored contact lenses for natural enhancement.',
    style: 'Natural',
    gallery: ['/images/freshkon-mosaic-color-ainak.pk_.jpg', '/images/contact-lenses-solution-bottle-banner_33099-1916.jpg'],
    featured: true,
    bestSeller: true
  },
  {
    id: 'lens-6',
    name: 'Air Optix Colors',
    price: 4200,
    category: 'Colored Lenses',
    brand: 'Alcon',
    material: 'Lotrafilcon B',
    shape: 'Round',
    rim: 'Full Rim',
    gender: 'Unisex',
    frameColor: 'Brilliant Blue',
    image: '/images/freshkon-mosaic-color-ainak.pk_.jpg',
    colors: [
      { name: 'Brilliant Blue', hex: '#0066CC' },
      { name: 'Gemstone Green', hex: '#228B22' },
      { name: 'Honey', hex: '#FFB347' },
      { name: 'Brown', hex: '#964B00' }
    ],
    sizes: ['8.6mm', '14.2mm'],
    lensTypes: ['Monthly'],
    features: ['Breathable', 'Color Blend Technology'],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: 'In Stock',
    description: 'Monthly colored contact lenses with advanced breathability.',
    style: 'Modern',
    gallery: ['/images/freshkon-mosaic.jpg'],
    featured: false,
    bestSeller: false
  }
];

const sampleProducts = [
  {
    name: "Classic Aviator Sunglasses",
    price: 2500,
    category: "Sunglasses",
    material: "Metal",
    shape: "Aviator",
    rim: "Full Rim",
    style: "Classic",
    colors: [{ name: "Gold", hex: "#FFD700" }],
    features: ["uv-protection", "polarized"],
    image: "/images/sunglasses.webp",
    featured: true,
    bestSeller: false,
    bestSelling: false,
    brand: "EyeWear Pro",
    gender: "Unisex",
    frameColor: "Gold",
    sizes: ["Medium", "Large"],
    lensTypes: ["Non-Prescription"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Classic aviator sunglasses with premium gold frame and UV protection."
  },
  {
    name: "Eco-Friendly Bamboo Frames",
    price: 3200,
    category: "fashion-glasses",
    material: "Wood",
    shape: "Rectangle",
    rim: "Full Rim",
    style: "Eco Friendly",
    colors: [{ name: "Brown", hex: "#8B4513" }],
    features: ["lightweight", "eco-friendly", "hypoallergenic"],
    image: "/images/eyeglasses.webp",
    featured: false,
    bestSeller: true,
    bestSelling: true,
    brand: "Green Vision",
    gender: "Unisex",
    frameColor: "Natural Brown",
    sizes: ["Small", "Medium"],
    lensTypes: ["Prescription", "Blue-Light"],
    discount: { hasDiscount: true, discountPercentage: 15 },
    status: "In Stock",
    description: "Sustainable bamboo frames perfect for environmentally conscious customers."
  },
  {
    name: "Bold Statement Glasses",
    price: 2800,
    category: "fashion-glasses",
    material: "Acetate",
    shape: "Cat Eye",
    rim: "Full Rim",
    style: "Bold",
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["bold-design", "lightweight", "durable"],
    image: "/images/eyeglasses.webp",
    featured: true,
    bestSeller: false,
    bestSelling: false,
    brand: "Bold Vision",
    gender: "Women",
    frameColor: "Matte Black",
    sizes: ["Medium"],
    lensTypes: ["Prescription", "Non-Prescription"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Make a bold statement with these striking cat-eye frames."
  },
  {
    name: "Retro Round Glasses",
    price: 2200,
    category: "reading-glasses",
    material: "Metal",
    shape: "Round",
    rim: "Full Rim",
    style: "Retro",
    colors: [{ name: "Copper", hex: "#B87333" }],
    features: ["vintage-style", "lightweight", "adjustable-nose-pads"],
    image: "/images/eyeglasses.webp",
    featured: false,
    bestSeller: true,
    bestSelling: true,
    brand: "Vintage Look",
    gender: "Unisex",
    frameColor: "Antique Copper",
    sizes: ["Small", "Medium"],
    lensTypes: ["Prescription", "Reading"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Classic round frames with a vintage copper finish."
  },
  {
    name: "Street Style Urban Frames",
    price: 2600,
    category: "sports-glasses",
    material: "Plastic",
    shape: "Square",
    rim: "Full Rim",
    style: "Street Style",
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["urban-design", "impact-resistant", "uv-protection"],
    image: "/images/sunglasses.webp",
    featured: false,
    bestSeller: false,
    bestSelling: false,
    brand: "Urban Edge",
    gender: "Men",
    frameColor: "Matte Black",
    sizes: ["Medium", "Large"],
    lensTypes: ["Non-Prescription"],
    discount: { hasDiscount: true, discountPercentage: 10 },
    status: "In Stock",
    description: "Urban street style frames perfect for the modern trendsetter."
  },
  {
    name: "Artsy Designer Frames",
    price: 3500,
    category: "computer-glasses",
    material: "Acetate",
    shape: "Geometric",
    rim: "Full Rim",
    style: "Artsy",
    colors: [{ name: "Tortoise", hex: "#D2691E" }],
    features: ["designer-style", "unique-design", "lightweight"],
    image: "/images/eyeglasses.webp",
    featured: true,
    bestSeller: false,
    bestSelling: false,
    brand: "Art Vision",
    gender: "Women",
    frameColor: "Tortoise Shell",
    sizes: ["Medium"],
    lensTypes: ["Prescription", "Progressive"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Unique geometric frames for the artistic and creative individual."
  }
];

export { sampleLensProducts };
export default sampleProducts;
