// Sample products with style data for testing style filtering
const sampleProducts = [
  {
    name: "Classic Aviator Sunglasses",
    price: 2500,
    category: "Sunglasses",
    material: "Metal",
    shape: "Aviator",
    rim: "Full Rim",
    style: "Classic",
    colors: [{ name: "Gold", hex: "#FFD700" }],
    features: ["uv-protection", "polarized"],
    image: "/images/sunglasses.webp",
    featured: true,
    bestSeller: false,
    brand: "EyeWear Pro",
    gender: "Unisex",
    frameColor: "Gold",
    sizes: ["Medium", "Large"],
    lensTypes: ["Non-Prescription"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Classic aviator sunglasses with premium gold frame and UV protection."
  },
  {
    name: "Eco-Friendly Bamboo Frames",
    price: 3200,
    category: "Eyeglasses",
    material: "Wood",
    shape: "Rectangle",
    rim: "Full Rim",
    style: "Eco Friendly",
    colors: [{ name: "Brown", hex: "#8B4513" }],
    features: ["lightweight", "eco-friendly", "hypoallergenic"],
    image: "/images/eyeglasses.webp",
    featured: false,
    bestSeller: true,
    brand: "Green Vision",
    gender: "Unisex",
    frameColor: "Natural Brown",
    sizes: ["Small", "Medium"],
    lensTypes: ["Prescription", "Blue-Light"],
    discount: { hasDiscount: true, discountPercentage: 15 },
    status: "In Stock",
    description: "Sustainable bamboo frames perfect for environmentally conscious customers."
  },
  {
    name: "Bold Statement Glasses",
    price: 2800,
    category: "Eyeglasses",
    material: "Acetate",
    shape: "Cat Eye",
    rim: "Full Rim",
    style: "Bold",
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["bold-design", "lightweight", "durable"],
    image: "/images/eyeglasses.webp",
    featured: true,
    bestSeller: false,
    brand: "Bold Vision",
    gender: "Women",
    frameColor: "Matte Black",
    sizes: ["Medium"],
    lensTypes: ["Prescription", "Non-Prescription"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Make a bold statement with these striking cat-eye frames."
  },
  {
    name: "Retro Round Glasses",
    price: 2200,
    category: "Eyeglasses",
    material: "Metal",
    shape: "Round",
    rim: "Full Rim",
    style: "Retro",
    colors: [{ name: "Copper", hex: "#B87333" }],
    features: ["vintage-style", "lightweight", "adjustable-nose-pads"],
    image: "/images/eyeglasses.webp",
    featured: false,
    bestSeller: true,
    brand: "Vintage Look",
    gender: "Unisex",
    frameColor: "Antique Copper",
    sizes: ["Small", "Medium"],
    lensTypes: ["Prescription", "Reading"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Classic round frames with a vintage copper finish."
  },
  {
    name: "Street Style Urban Frames",
    price: 2600,
    category: "Sunglasses",
    material: "Plastic",
    shape: "Square",
    rim: "Full Rim",
    style: "Street Style",
    colors: [{ name: "Black", hex: "#000000" }],
    features: ["urban-design", "impact-resistant", "uv-protection"],
    image: "/images/sunglasses.webp",
    featured: false,
    bestSeller: false,
    brand: "Urban Edge",
    gender: "Men",
    frameColor: "Matte Black",
    sizes: ["Medium", "Large"],
    lensTypes: ["Non-Prescription"],
    discount: { hasDiscount: true, discountPercentage: 10 },
    status: "In Stock",
    description: "Urban street style frames perfect for the modern trendsetter."
  },
  {
    name: "Artsy Designer Frames",
    price: 3500,
    category: "Eyeglasses",
    material: "Acetate",
    shape: "Geometric",
    rim: "Full Rim",
    style: "Artsy",
    colors: [{ name: "Tortoise", hex: "#D2691E" }],
    features: ["designer-style", "unique-design", "lightweight"],
    image: "/images/eyeglasses.webp",
    featured: true,
    bestSeller: false,
    brand: "Art Vision",
    gender: "Women",
    frameColor: "Tortoise Shell",
    sizes: ["Medium"],
    lensTypes: ["Prescription", "Progressive"],
    discount: { hasDiscount: false, discountPercentage: 0 },
    status: "In Stock",
    description: "Unique geometric frames for the artistic and creative individual."
  }
];

export default sampleProducts;
